// Generated by folio/tools/gen.zig from src/token.zig.
// DO NOT EDIT. Run `zig build gen` to regenerate.

#ifndef FOLIO_TREE_SITTER_CONSTANTS_H
#define FOLIO_TREE_SITTER_CONSTANTS_H

// Structural source characters.
#define FOLIO_SCENE_SIGIL   ':'
#define FOLIO_BEAT_SIGIL    ';'
#define FOLIO_BLOCK_OPEN    '{'
#define FOLIO_BLOCK_CLOSE   '}'
#define FOLIO_DEFER_SIGIL   '%'
#define FOLIO_INSTANT_SIGIL '#'
#define FOLIO_CHAR_SIGIL    '@'
#define FOLIO_QUOTE_DOUBLE  '"'
#define FOLIO_QUOTE_SINGLE  '\''
#define FOLIO_BACKSLASH     '\\'

#endif
