// Generated by folio/tools/gen.zig from src/token.zig.
// DO NOT EDIT. Run `zig build gen` to regenerate.

module.exports = {
    // Structural source characters.
    SCENE_SIGIL:   ':',
    BEAT_SIGIL:    ';',
    BLOCK_OPEN:    '{',
    BLOCK_CLOSE:   '}',
    DEFER_SIGIL:   '%',
    INSTANT_SIGIL: '#',
    CHAR_SIGIL:    '@',
    QUOTE_DOUBLE:  '"',
    QUOTE_SINGLE:  "'",
    BACKSLASH:     '\\',
};
